# 链接样式，参考 http://jekyllrb.com/docs/permalinks
permalink: /:categories/:year-:month/:title.html

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true
paginate: 5

markdown: redcarpet             # markdown 语法解释引擎
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
# 参考 http://github.com/vmg/redcarpet/blob/master/README.markdown

# 核心设置
title : Caijinlin's blog
tagline: Site Tagline
keywords : caijinliin, linux, php, Mysql, c++,git
description: 蔡金林的技术博客
author :
  name : caijinlin
  email : 1399534656@qq.com
  github : caijinlin
  gitcafe : 
  twitter :
  facebook :
  feedburner :
  weibo : sclgcaijinlin

# 域名连接
#production_url : //ihavee.github.io

# Jekyll Bootstrap
JB :
  version : 0.3.0

  BASE_PATH : false                 # 如果不懂参数，请不要更改
  ASSET_PATH : false                # 同上

  # page
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  # 评论，provider 留空或 false 关闭评论
  comments :
    provider : duoshuo                     # 采用那种评论，可填 duoshuo 或 disqus 或其他 ...
    disqus :
      short_name :
    livefyre :
      site_id :
    intensedebate :
      account :
    facebook :
      appid :
      num_posts:
      width: 580
      colorscheme: light
    duoshuo :
      name : cjl              # 多说上获取的 shortname
      rcomments :                   # 首页侧边栏最新评论
        num: 10                     # 最新评论显示条数
        avatar : 1                   # 最新评论是否显示头像
        time: 1
        title : 1
        admin : 1
        length : 12                 # 最新评论显示的长度
      rvisitors :                   # 首页侧边栏最新访客
        num : 12                    # 最新访客数目
        size : 45                   # 最新访客头像的尺寸

  # 网站统计
  analytics :
    provider :                      # 采用那种统计，可填 baidu 或 google 或其他 ...
    google :
        tracking_id : 'UA-123-12'
    getclicky :
        site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik
    baidu :
        siteid: 707xxxxxxxxxxxxxxxxxxxxx        # 百度统计 js 代码后的字符串

  # 一键分享
  sharing :
    provider :  baidu                     # 参考 _includes/JB/sharing

  # CDN 加速资源
  cdn :
    jquery :
      js : //cdn.bootcss.com/jquery/2.1.0/jquery.min.js
    webfont : true                  # google-fonts 开关，false 为关，留空或 true 为打开
    google-fonts :
      js : //cdn.bootcss.com/webfont/1.3.0/webfont.min.js
    font-awesome :
      css : //cdn.bootcss.com/font-awesome/4.0.3/css/font-awesome.min.css
    bootstrap :
      js : //cdn.bootcss.com/twitter-bootstrap/3.1.1/js/bootstrap.min.js
      css : //cdn.bootcss.com/twitter-bootstrap/3.1.1/css/bootstrap.min.css
    fancybox :
      js : //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.js
      css : //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.css

  # 友情链接
  blogroll : false                   # true 开启，留空或 false 关闭
  brlist :
    - text : Caijinlin's Space
      url : wwww.caijinlin.com
